name: Deploy Frontend (Vite)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Set VITE env variable
        run: echo "VITE_BASE_API_URL=${{ secrets.VITE_BASE_API_URL }}" >> .env

      - name: Build the Vite app
        run: yarn build

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Restart frontend with PM2
        run: |
          pm2 delete budget-planner-frontend || true
          pm2 start yarn --name budget-planner-frontend -- start
          pm2 save
